### ISSUE TITLE
Support initialization from current timestamp/proposal

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hcs-governance#7]
Currently on initialization, the server infrastructure will process all messages in the .env files HCS topic. It will attempt to recalculate state based on this information. However, some users may wish to process _future_ messages, without the computational burden of processing _historical_ messages. We should provide a command that enables users to choose a particular timestamp, or proposal, and process from that point -> forward, rather than requiring all users to process all messages. This will result in some UI implications, such as notice that software ran in "light mode" (or whatever we end up calling it) may not contain all historical votes/proposals that have ever taken place.

**Comment by bugbytesinc** [comment]
Preliminary plan: introduce an environmental variable `HISTORY_STARTING_DATE` that will have the HAPI format of '000000.00000', the algorithm will simply start the startup replay process >= that date.  

- As a side affect, any ballot vote that is cast for a proposal that was defined prior to the date will be considered invalid and ignored.  This can be seen in the server logs if verbose logging is enabled.
- If `HISTORY_STARTING_DATE` is not specified in the environment, the algorithm will replay the entirety of the target HCS message stream.
- If `HISTOR_STARTING_DATE` is in the future, a startup validation check will be thrown and the service will not start.

**Comment by bugbytesinc** [comment]
How about naming the variable `HCS_START_DATE` this may be more 'consistent' with the other environmental variables.
